name: Lint the sources
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Try pulling tarantool
        run: docker pull tarantool/tarantool
      - name: Lint the sources
        run: python3 lint/lint.py
        shell: bash
